sonar.projectKey=pruebas-andre
sonar.projectName=EntreAulas Back RQ10-11-13-29-31
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.inclusions=src/app.ts,src/middleware/auth.ts,src/modules/auth/auth.routes.ts,src/modules/academic/teachers.routes.ts,src/modules/academic/teachers-list.service.ts,src/modules/academic/users.routes.ts,src/modules/academic/users.controller.ts,src/modules/analytics/teachers-analytics.routes.ts,src/modules/ai-summary/ai.routes.ts,src/modules/ai-summary/ai-open-texts.ts,src/modules/ai-summary/ai.service.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts
