import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'node',
    include: ['src/test/unit/**/*.test.ts'],
    // Integración, defects y *.test.ts colocalizados usan vi.mock: no van en npm test.
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      'src/test/defects/**',
    ],
    setupFiles: ['src/test/setup.ts'],
    globals: false,
    coverage: {
      provider: 'v8',
      reportsDirectory: './coverage',
      reporter: ['text', 'html', 'lcov'],
      reportOnFailure: true,
      // Alineado con sonar.inclusions (lcov que lee Sonar).
      include: [
        'src/middleware/auth.ts',
        'src/utils/passwordSecurity.ts',
        'src/shared/errors.ts',
        'src/shared/logger.ts',
        'src/modules/auth/**/*.ts',
        'src/modules/academic/users.controller.ts',
        'src/modules/academic/estudiante-materias.ts',
        'src/modules/analytics/calificaciones.ts',
        'src/modules/analytics/coordinador-resumen.ts',
        'src/modules/analytics/reporte-exportacion.ts',
        'src/modules/analytics/teachers-analytics.service.ts',
        'src/modules/analytics/teachers-analytics.routes.ts',
        'src/modules/ai-summary/ai.service.ts',
        'src/modules/ai-summary/ai.routes.ts',
        'src/modules/evaluations/qr-resolucion.ts',
        'src/modules/evaluations/qr-batch.ts',
        'src/modules/evaluations/qr-auto-enroll.ts',
        'src/modules/evaluations/qr-share-email.ts',
        'src/modules/evaluations/qr-evaluaciones.routes.ts',
      ],
      exclude: [
        'src/test/**',
        'src/scripts/**',
        'src/docs/**',
        'src/routes/**',
        '**/*.test.ts',
        '**/*.d.ts',
        'src/modules/**/*.types.ts',
        'src/server.ts',
        'src/modules/teachers.router.ts',
        'src/modules/academic/courses.routes.ts',
        'src/modules/analytics/coordinador.routes.ts',
        'src/modules/evaluations/evaluations.routes.ts',
        'src/modules/evaluations/student-evaluations.routes.ts',
        'src/modules/evaluations/resultados.routes.ts',
      ],
    },
  },
})
